---
title: "Homework 5"
output: github_document
---

```{r setup, include = FALSE, message = FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r initial, message = FALSE}
library(tidyverse)
library(ggplot2)
library(patchwork)
```

## Problem 2

```{r hm_summary}
homicides = read_csv("data/homicide-data.csv") %>%
  mutate(city_state = str_c(city, ", ", state),
         city_state = recode(city_state, "Tulsa, AL" = "Tulsa, OK"),
         unsol_hm = ifelse(disposition == "Closed without arrest" | disposition == "Open/No arrest", TRUE, FALSE)
         ) %>%
  relocate(city_state, .after = state) %>%
  
  group_by(city_state) %>%
  summarise(tot_hm = n_distinct(uid),
        tot_unsol_hm = n_distinct(uid[unsol_hm == TRUE]))
```

```{r hm_baltimore}
balt_tot = homicides %>%
  filter(city_state == "Baltimore, MD") %>%
  pull(tot_hm)

balt_unsol = homicides %>%
  filter(city_state == "Baltimore, MD") %>%
  pull(tot_unsol_hm)

prop.test(x = balt_unsol, 
          n = balt_tot) %>%
  broom::tidy() %>%
  select(estimate, starts_with("conf")) 
```

```{r hm_all_cities}
prop_unsol = function(city) {
  
  tot = homicides %>%
    filter(city_state == city) %>%
    pull(tot_hm)
  
  unsol = homicides %>%
    filter(city_state == city) %>%
    pull(tot_unsol_hm)
  
  prop.test(x = unsol, 
            n = tot) %>%
    broom::tidy() %>%
    select(estimate, starts_with("conf"))
 
}

hm_listcol = homicides %>% 
  mutate(summary = map(city_state, prop_unsol)) %>%
  unnest(summary)
```

```{r hm_plot, fig.width = 9, fig.asp = 0.6}
hm_listcol %>% 
  mutate(city_state = fct_reorder(city_state, estimate)) %>%
  ggplot(aes(x = city_state, y = estimate, color = city_state)) +
  geom_point() +
  geom_errorbar(aes(ymin = conf.low, ymax = conf.high)) +
  labs(title = "Estimates and confidence intervals for proportions of unsolved homicides, by city",
       x = "City",
       y = "Estimated share of unsolved homicides"
  ) +
  theme(legend.position = "none",
        plot.title = element_text(size = 11, hjust = 0.5),
        axis.text.x = element_text(angle = 45, hjust = 1))
```

## Problem 3

```{r sim}
sim = function(n = 30, mu = 0, sigma = 5) {
  
  sim_data = tibble(x = rnorm(n, mean = mu, sd = sigma))
  
  sim_data %>%
    t.test(mu = 0) %>%
    broom::tidy() %>%
    select(estimate, p.value)
}

sim(mu = 5)

sim_results = 
  tibble(mean = c(0, 1, 2, 3, 4, 5, 6)) %>% 
  mutate(output_lists = map(.x = mean, ~rerun(5000, sim(mu = .x))),
    estimate_dfs = map(output_lists, bind_rows)) %>% 
  select(-output_lists) %>% 
  unnest(estimate_dfs) %>%
  mutate(reject_null = ifelse(p.value < 0.05, TRUE, FALSE))
```

```{r sim_plot_i, fig.width = 9, fig.asp = 0.6}
sim_results %>%
  group_by(mean) %>%
  summarise(prop_null_reject = sum(reject_null) / n()) %>%
  ggplot(aes(x = mean, y = prop_null_reject)) +
  geom_point() +
  geom_line() +
  labs(title = "Relationship between effect size and power",
       x = "Population mean",
       y = "Proportion of times null is rejected") +
  theme(plot.title = element_text(size = 11))
```

```{r sim_plot_ii, fig.width = 9, fig.asp = 0.6}
est_mu = sim_results %>%
  group_by(mean) %>%
  summarise(avg_est_mu = mean(estimate)) %>%
  ggplot(aes(x = mean, y = avg_est_mu)) +
  geom_point() +
  geom_line() +
  labs(title = "Population vs. average estimated mean",
       x = "Population mean",
       y = "Average estimate of mean") +
  theme(plot.title = element_text(size = 11))

est_mu_null_reject = sim_results %>%
  filter(reject_null == TRUE) %>%
  group_by(mean) %>%
  summarise(avg_est_mu = mean(estimate)) %>%
  ggplot(aes(x = mean, y = avg_est_mu)) +
  geom_point() +
  geom_line() +
  labs(title = "Population vs. average estimated mean (H0 rejected)",
       x = "Population mean",
       y = "Average estimate of mean (H0 rejected)") +
  theme(plot.title = element_text(size = 11))

est_mu + est_mu_null_reject
```



